version: '3'
services:
  reverse-proxy:
    image: nginx:stable-bullseye-perl
    container_name: nginx_container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
    networks:
      - reverse-proxy-net
      
  back-service:
    build: .
    container_name: backend-container
    environment:
      SPRING_POSTGRES_URL: my-db-test.io
      DB_PORT: 5432
      DB_USER: myapplication
      DB_PASSWORD: M3P@ssw0rd!
      DB_NAME: postgres
    depends_on:
      - reverse-proxy
    networks:
      - app-net
      - reverse-proxy-net
    ports:
      - "8001:80"  

  front-service:
    image: my-registry.io/my-application/front:1.0
    container_name: frontend-container
    depends_on:
      - reverse-proxy
    ports:
      - 8002:80
    networks:
      - app-net
      - reverse-proxy-net

networks:
  reverse-proxy-net:
  app-net: